#pragma once

#include <cstdint>

namespace cfg {
constexpr int TargetFps = 60;
constexpr int WindowWidth = 1280;
constexpr int WindowHeight = 720;
constexpr int ServerPort = 42069;
constexpr int MaxPlayers = 4;
constexpr int MinPlayers = 2;
constexpr int MapCount = 3;
constexpr float FixedDt = 1.0F / static_cast<float>(TargetFps);
constexpr float WorldWidth = 2200.0F;
constexpr float WorldHeight = 1400.0F;
constexpr float PlayerRadius = 18.0F;
constexpr float PlayerHitRadius = 46.0F;
constexpr float PlayerSpeed = 356.25F;
constexpr float DashSpeed = 860.0F;
constexpr float DashSeconds = 0.14F;
constexpr float DashCooldownSeconds = 1.15F;
constexpr float PlayerMaxHealth = 100.0F;
constexpr float RespawnSeconds = 3.0F;
constexpr float SpawnProtectionSeconds = 2.5F;
constexpr float BulletRadius = 4.0F;
constexpr float GrenadeRadius = 8.0F;
constexpr float GrenadeFuseSeconds = 0.37F;         // was 0.55 — 50% faster
constexpr float GrenadeExplosionRadius = 115.0F * 1.30F * 1.30F;
constexpr float GrenadeDamage = cfg::PlayerMaxHealth;
constexpr float GrenadeThrowSpeed = 720.0F;
constexpr float GrenadeMinFlightSeconds = 0.12F;    // was 0.18 — 50% faster
constexpr float GrenadeMaxFlightSeconds = 0.52F;    // was 0.78 — 50% faster
constexpr float GrenadeArcHeight = 46.0F;
constexpr float BarrierWidth = 84.0F;
constexpr float BarrierHeight = 28.0F;
constexpr float BarrierHealth = 90.0F;
constexpr float BarrierPlaceDistance = 70.0F;
constexpr float SnapshotSeconds = 1.0F / 20.0F;
constexpr float ClientSendSeconds = 1.0F / 30.0F;
constexpr float ClientSilenceThreshold = 6.0F;
constexpr float ReconnectWindowSeconds = 15.0F;
constexpr float ServerTimeoutSeconds = 10.0F;
constexpr float ConnectTimeoutSeconds = 6.0F;
constexpr float ClientTimeoutSeconds = 15.0F;
constexpr float DefaultMatchMinutes = 3.0F;
constexpr float MatchCountdownSeconds = 3.0F;
constexpr int DefaultScoreLimit = 15;
constexpr int MaxBullets = 128;
constexpr int MaxGrenades = 32;
constexpr int MaxBarriers = 24;
constexpr int MaxRecentKills = 6;
constexpr float KillFeedDuration = 7.0F;
constexpr int PacketBytes = 4096;
constexpr int NameBytes = 24;
constexpr int AddressBytes = 64;
constexpr int RoomCodeLength = 4;
constexpr int RoomCodeBytes = RoomCodeLength + 1;
constexpr int RifleAmmo = 30;
constexpr int PistolAmmo = 15;
constexpr int SniperAmmo = 1;
constexpr int ShotgunAmmo = 6;
constexpr int RifleGrenades = 4;
constexpr int RifleBarriers = 4;
constexpr int PistolGrenades = 10;
constexpr int PistolBarriers = 10;
constexpr int SniperGrenades = 1;
constexpr int SniperBarriers = 1;
constexpr int ShotgunGrenades = 3;
constexpr int ShotgunBarriers = 5;
constexpr float ReloadSeconds = 1.25F;
constexpr float MenuColumnX = 54.0F;
constexpr float MenuTopY = 92.0F;
constexpr float ButtonWidth = 330.0F;
constexpr float ButtonHeight = 48.0F;
constexpr float ButtonGap = 14.0F;
constexpr std::uint32_t ProtocolMagic = 0x54544F50U;
constexpr std::uint16_t ProtocolVersion = 1;
}
